# Generated by Django 5.2.15 on 2026-08-20 12:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('buildings', '0005_single_building'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان')),
                ('description', models.TextField(blank=True, default='', verbose_name='توضیحات')),
                ('status', models.CharField(choices=[('Draft', 'پیش\u200cنویس'), ('Active', 'فعال'), ('Closed', 'بسته\u200cشده')], default='Draft', max_length=20, verbose_name='وضعیت')),
                ('starts_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان شروع')),
                ('ends_at', models.DateTimeField(verbose_name='زمان پایان')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='زمان بروزرسانی')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_polls', to=settings.AUTH_USER_MODEL, verbose_name='ایجادکننده')),
                ('target_units', models.ManyToManyField(blank=True, help_text='اگر خالی باشد، همه واحدها هدف هستند.', related_name='polls', to='buildings.unit', verbose_name='واحدهای هدف')),
            ],
            options={
                'verbose_name': 'نظرسنجی',
                'verbose_name_plural': 'نظرسنجی\u200cها',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PollOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255, verbose_name='متن گزینه')),
                ('position', models.PositiveSmallIntegerField(default=0, help_text='عدد کوچک\u200cتر، بالاتر نشان داده می\u200cشود.', verbose_name='ترتیب نمایش')),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='polls.poll', verbose_name='نظرسنجی')),
            ],
            options={
                'verbose_name': 'گزینه نظرسنجی',
                'verbose_name_plural': 'گزینه\u200cهای نظرسنجی',
                'ordering': ['position', 'id'],
                'unique_together': {('poll', 'position')},
            },
        ),
    ]
