# Generated by Django 5.2.15 on 2026-08-21 07:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='polloption',
            unique_together=set(),
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ثبت رأی')),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='polls.polloption', verbose_name='گزینه')),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='polls.poll', verbose_name='نظرسنجی')),
                ('resident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to=settings.AUTH_USER_MODEL, verbose_name='ساکن')),
            ],
            options={
                'verbose_name': 'رأی',
                'verbose_name_plural': 'رأی\u200cها',
                'constraints': [models.UniqueConstraint(fields=('poll', 'resident'), name='unique_vote_per_resident_per_poll')],
            },
        ),
    ]
