class PollMessages:
    POLL_CREATED = "نظرسنجی با موفقیت ایجاد شد."
    POLL_UPDATED = "نظرسنجی با موفقیت به‌روزرسانی شد."
    POLL_NOT_FOUND = "نظرسنجی مورد نظر یافت نشد."
    POLL_PUBLISHED = "نظرسنجی با موفقیت منتشر شد."
    POLL_CLOSED = "نظرسنجی با موفقیت بسته شد."
    TITLE_REQUIRED = "عنوان نظرسنجی الزامی است."
    AT_LEAST_TWO_OPTIONS = "حداقل دو گزینه برای نظرسنجی الزامی است."
    DUPLICATE_OPTIONS = "گزینه‌های تکراری مجاز نیستند."
    ENDS_AT_IN_PAST = "زمان پایان باید در آینده باشد."
    CANNOT_PUBLISH_WITHOUT_STARTS_AT = "برای انتشار، زمان شروع الزامی است."
    ONLY_DRAFT_CAN_BE_PUBLISHED = "فقط نظرسنجی‌های در وضعیت پیش‌نویس قابل انتشار هستند."
    ONLY_ACTIVE_CAN_BE_CLOSED = "فقط نظرسنجی‌های فعال قابل بسته‌شدن هستند."
    ONLY_DRAFT_CAN_BE_EDITED = "فقط نظرسنجی‌های در وضعیت پیش‌نویس قابل ویرایش هستند."