# Generated by Django 5.2.15 on 2026-08-09 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام امکان')),
                ('description', models.TextField(blank=True, default='', verbose_name='توضیحات')),
                ('operating_rules', models.CharField(blank=True, default='', help_text='مثلاً: 08:00 تا 22:00', max_length=255, verbose_name='قوانین و ساعات کاری')),
                ('is_active', models.BooleanField(default=True, help_text='غیرفعال کردن برای تعمیرات یا نگهداری', verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'امکان',
                'verbose_name_plural': 'امکانات',
                'ordering': ['name'],
            },
        ),
    ]
