# Generated by Django 5.2.15 on 2026-08-08 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="unitcharge",
            name="paid_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
