# Generated by Django 5.2.15 on 2026-08-07 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("maintenance", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="servicerequest",
            name="cost",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="servicerequest",
            name="is_settled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="servicerequest",
            name="payment_method",
            field=models.CharField(
                blank=True,
                choices=[
                    ("EQUAL_SPLIT", "Equal Split"),
                    ("REQUESTER_ONLY", "Requester Only"),
                    ("BUILDING_WALLET", "Building Wallet"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
