# Generated by Django 5.2.15 on 2026-08-07 07:04

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("buildings", "0002_alter_unit_building_alter_unit_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="building",
            name="building_wallet_balance",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=12
            ),
        ),
        migrations.AddField(
            model_name="unit",
            name="debt",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=12
            ),
        ),
    ]
