# Generated by Django 5.2.15 on 2026-08-11 14:36

from django.db import migrations, models


def mark_owned_units_occupied(apps, schema_editor):
    """
    Units that already have a resident linked start out occupied; leaving them
    on the "Vacant" default would misreport every existing record.
    """
    Unit = apps.get_model("buildings", "Unit")
    Unit.objects.filter(owner__isnull=False).update(occupancy_status="Occupied")


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0003_building_building_wallet_balance_unit_debt'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='occupancy_status',
            field=models.CharField(choices=[('Occupied', 'Occupied'), ('Vacant', 'Vacant'), ('UnderRenovation', 'Under Renovation')], default='Vacant', max_length=20),
        ),
        migrations.RunPython(mark_owned_units_occupied, migrations.RunPython.noop),
    ]
