# Generated by Django 5.2.15 on 2026-08-13 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_username_remove_user_is_disabled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('resident', 'Resident'), ('manager', 'Manager'), ('admin', 'Admin'), ('service_staff', 'Service Staff')], default='resident', max_length=20),
        ),
    ]
